name: Release Drafter

on:
  push:
    branches:
      - main
      - master

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/release-drafter
      - uses: release-drafter/release-drafter@v5
        if: ${{ !env.ACT }}
        with:
          config-name: "release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}